lockservice_database_1 is up-to-date
lockservice_lockserv_1 is up-to-date
Attaching to lockservice_database_1, lockservice_lockserv_1
[36mdatabase_1  |[0m 2017-12-08T16:45:42.897+0000 I JOURNAL  [initandlisten] journal dir=/data/db/journal
[36mdatabase_1  |[0m 2017-12-08T16:45:42.897+0000 I JOURNAL  [initandlisten] recover : no journal files present, no recovery needed
[36mdatabase_1  |[0m 2017-12-08T16:45:44.112+0000 I JOURNAL  [initandlisten] preallocateIsFaster=true 18.08
[36mdatabase_1  |[0m 2017-12-08T16:45:44.395+0000 I JOURNAL  [initandlisten] preallocateIsFaster=true 3.06
[36mdatabase_1  |[0m 2017-12-08T16:45:45.681+0000 I JOURNAL  [initandlisten] preallocateIsFaster=true 3.2
[36mdatabase_1  |[0m 2017-12-08T16:45:45.681+0000 I JOURNAL  [initandlisten] preallocating a journal file /data/db/journal/prealloc.0
[36mdatabase_1  |[0m 2017-12-08T16:45:47.238+0000 I JOURNAL  [initandlisten] preallocating a journal file /data/db/journal/prealloc.1
[36mdatabase_1  |[0m 2017-12-08T16:45:49.001+0000 I JOURNAL  [initandlisten] preallocating a journal file /data/db/journal/prealloc.2
[36mdatabase_1  |[0m 2017-12-08T16:45:50.875+0000 I JOURNAL  [durability] Durability thread started
[36mdatabase_1  |[0m 2017-12-08T16:45:50.875+0000 I JOURNAL  [journal writer] Journal writer thread started
[36mdatabase_1  |[0m 2017-12-08T16:45:50.912+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=c597a85cae60
[36mdatabase_1  |[0m 2017-12-08T16:45:50.912+0000 I CONTROL  [initandlisten] 
[36mdatabase_1  |[0m 2017-12-08T16:45:50.912+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
[36mdatabase_1  |[0m 2017-12-08T16:45:50.912+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
[36mdatabase_1  |[0m 2017-12-08T16:45:50.912+0000 I CONTROL  [initandlisten] 
[36mdatabase_1  |[0m 2017-12-08T16:45:50.912+0000 I CONTROL  [initandlisten] db version v3.0.2
[36mdatabase_1  |[0m 2017-12-08T16:45:50.912+0000 I CONTROL  [initandlisten] git version: 6201872043ecbbc0a4cc169b5482dcf385fc464f
[36mdatabase_1  |[0m 2017-12-08T16:45:50.912+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
[36mdatabase_1  |[0m 2017-12-08T16:45:50.912+0000 I CONTROL  [initandlisten] build info: Linux ip-10-171-120-232 3.2.0-4-amd64 #1 SMP Debian 3.2.46-1 x86_64 BOOST_LIB_VERSION=1_49
[36mdatabase_1  |[0m 2017-12-08T16:45:50.912+0000 I CONTROL  [initandlisten] allocator: tcmalloc
[36mdatabase_1  |[0m 2017-12-08T16:45:50.912+0000 I CONTROL  [initandlisten] options: {}
[36mdatabase_1  |[0m 2017-12-08T16:45:50.914+0000 I INDEX    [initandlisten] allocating new ns file /data/db/local.ns, filling with zeroes...
[36mdatabase_1  |[0m 2017-12-08T16:45:50.984+0000 I STORAGE  [FileAllocator] allocating new datafile /data/db/local.0, filling with zeroes...
[36mdatabase_1  |[0m 2017-12-08T16:45:50.984+0000 I STORAGE  [FileAllocator] creating directory /data/db/_tmp
[36mdatabase_1  |[0m 2017-12-08T16:45:51.008+0000 I STORAGE  [FileAllocator] done allocating datafile /data/db/local.0, size: 64MB,  took 0.01 secs
[36mdatabase_1  |[0m 2017-12-08T16:45:51.015+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
[36mdatabase_1  |[0m 2017-12-08T16:47:08.740+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.5:57892 #1 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:47:08.747+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.5:57894 #2 (2 connections now open)
[33mlockserv_1  |[0m 2017-12-08T17:01:15695592883000+0000 Starting Lock server
[36mdatabase_1  |[0m 2017-12-08T16:47:08.749+0000 I INDEX    [conn2] allocating new ns file /data/db/USEHASKELLDB.ns, filling with zeroes...
[33mlockserv_1  |[0m 2017-12-08T17:01:15695975746000+0000 Environment variable: LOCKSERV_PORT is not set. Defaulting to "8080"
[36mdatabase_1  |[0m 2017-12-08T16:47:08.824+0000 I STORAGE  [FileAllocator] allocating new datafile /data/db/USEHASKELLDB.0, filling with zeroes...
[33mlockserv_1  |[0m 2017-12-08T17:01:59552969424000+0000 Trying to lock f_1/testfile.
[36mdatabase_1  |[0m 2017-12-08T16:47:08.832+0000 I STORAGE  [FileAllocator] done allocating datafile /data/db/USEHASKELLDB.0, size: 64MB,  took 0.007 secs
[33mlockserv_1  |[0m 2017-12-08T17:01:59554109779000+0000 172.17.0.1:59516
[36mdatabase_1  |[0m 2017-12-08T16:47:08.840+0000 I NETWORK  [conn2] end connection 172.17.0.5:57894 (1 connection now open)
[33mlockserv_1  |[0m 2017-12-08T17:01:59554769470000+0000 Environment variable: MONGODB_DATABASE is not set. Defaulting to "USEHASKELLDB"
[36mdatabase_1  |[0m 2017-12-08T16:47:08.840+0000 I NETWORK  [conn1] end connection 172.17.0.5:57892 (1 connection now open)
[33mlockserv_1  |[0m 2017-12-08T17:01:59559028608000+0000 Environment variable: MONGODB_DATABASE is not set. Defaulting to "USEHASKELLDB"
[36mdatabase_1  |[0m 2017-12-08T16:47:09.203+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.5:57958 #3 (1 connection now open)
[33mlockserv_1  |[0m 172.17.0.1 - - [08/Dec/2017:17:01:59 +0000] "POST /lock HTTP/1.1" 200 - "" ""
[36mdatabase_1  |[0m 2017-12-08T16:47:09.210+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.5:57960 #4 (2 connections now open)
[33mlockserv_1  |[0m 2017-12-08T17:02:06422148279000+0000 Environment variable: MONGODB_DATABASE is not set. Defaulting to "USEHASKELLDB"
[36mdatabase_1  |[0m 2017-12-08T16:47:09.212+0000 I NETWORK  [conn4] end connection 172.17.0.5:57960 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:47:09.212+0000 I NETWORK  [conn3] end connection 172.17.0.5:57958 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:47:33.834+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.5:57996 #5 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:47:33.835+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.5:57998 #6 (2 connections now open)
[36mdatabase_1  |[0m 2017-12-08T16:47:33.835+0000 I NETWORK  [conn6] end connection 172.17.0.5:57998 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:47:33.835+0000 I NETWORK  [conn5] end connection 172.17.0.5:57996 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:47:37.570+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.5:58006 #7 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:47:37.572+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.5:58008 #8 (2 connections now open)
[36mdatabase_1  |[0m 2017-12-08T16:47:37.574+0000 I NETWORK  [conn8] end connection 172.17.0.5:58008 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:47:37.574+0000 I NETWORK  [conn7] end connection 172.17.0.5:58006 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:47:53.906+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.5:58046 #9 (1 connection now open)
[33mlockserv_1  |[0m 2017-12-08T17:02:06425238021000+0000  queue[["hello","8700"]]
[36mdatabase_1  |[0m 2017-12-08T16:47:53.914+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.5:58050 #10 (2 connections now open)
[33mlockserv_1  |[0m 2017-12-08T17:02:06425905880000+0000  nextuser  addr"hello" addr 172.17.0.1:47500
[33mlockserv_1  |[0m 2017-12-08T17:02:06426757435000+0000 Assigning lock to client on port 8700
[33mlockserv_1  |[0m 2017-12-08T17:02:06433895789000+0000 lockAvailable successfull
[33mlockserv_1  |[0m 2017-12-08T17:02:06434707812000+0000 Environment variable: MONGODB_DATABASE is not set. Defaulting to "USEHASKELLDB"
[33mlockserv_1  |[0m 172.17.0.1 - - [08/Dec/2017:17:02:06 +0000] "POST /unlock HTTP/1.1" 200 - "" ""
[36mdatabase_1  |[0m 2017-12-08T16:47:53.916+0000 I NETWORK  [conn10] end connection 172.17.0.5:58050 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:47:53.916+0000 I NETWORK  [conn9] end connection 172.17.0.5:58046 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:48:19.679+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.1:46562 #11 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:48:19.680+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.1:46566 #12 (2 connections now open)
[36mdatabase_1  |[0m 2017-12-08T16:48:19.682+0000 I NETWORK  [conn12] end connection 172.17.0.1:46566 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:48:19.682+0000 I NETWORK  [conn11] end connection 172.17.0.1:46562 (0 connections now open)
[36mdatabase_1  |[0m 2017-12-08T16:48:19.688+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.1:46594 #13 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:48:19.688+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.1:46598 #14 (2 connections now open)
[36mdatabase_1  |[0m 2017-12-08T16:48:19.690+0000 I NETWORK  [conn13] end connection 172.17.0.1:46594 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:48:19.690+0000 I NETWORK  [conn14] end connection 172.17.0.1:46598 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:57:59.814+0000 I CONTROL  [signalProcessingThread] got signal 15 (Terminated), will terminate after current cmd ends
[36mdatabase_1  |[0m 2017-12-08T16:57:59.814+0000 I CONTROL  [signalProcessingThread] now exiting
[36mdatabase_1  |[0m 2017-12-08T16:57:59.814+0000 I NETWORK  [signalProcessingThread] shutdown: going to close listening sockets...
[36mdatabase_1  |[0m 2017-12-08T16:57:59.814+0000 I NETWORK  [signalProcessingThread] closing listening socket: 5
[36mdatabase_1  |[0m 2017-12-08T16:57:59.814+0000 I NETWORK  [signalProcessingThread] closing listening socket: 6
[36mdatabase_1  |[0m 2017-12-08T16:57:59.814+0000 I NETWORK  [signalProcessingThread] removing socket file: /tmp/mongodb-27017.sock
[36mdatabase_1  |[0m 2017-12-08T16:57:59.814+0000 I NETWORK  [signalProcessingThread] shutdown: going to flush diaglog...
[36mdatabase_1  |[0m 2017-12-08T16:57:59.814+0000 I NETWORK  [signalProcessingThread] shutdown: going to close sockets...
[36mdatabase_1  |[0m 2017-12-08T16:57:59.814+0000 I STORAGE  [signalProcessingThread] shutdown: waiting for fs preallocator...
[36mdatabase_1  |[0m 2017-12-08T16:57:59.814+0000 I STORAGE  [signalProcessingThread] shutdown: final commit...
[36mdatabase_1  |[0m 2017-12-08T16:57:59.815+0000 I JOURNAL  [signalProcessingThread] journalCleanup...
[36mdatabase_1  |[0m 2017-12-08T16:57:59.815+0000 I JOURNAL  [signalProcessingThread] removeJournalFiles
[36mdatabase_1  |[0m 2017-12-08T16:57:59.822+0000 I JOURNAL  [signalProcessingThread] Terminating durability thread ...
[36mdatabase_1  |[0m 2017-12-08T16:57:59.917+0000 I JOURNAL  [journal writer] Journal writer thread stopped
[36mdatabase_1  |[0m 2017-12-08T16:57:59.917+0000 I JOURNAL  [durability] Durability thread stopped
[36mdatabase_1  |[0m 2017-12-08T16:57:59.917+0000 I STORAGE  [signalProcessingThread] shutdown: closing all files...
[36mdatabase_1  |[0m 2017-12-08T16:57:59.922+0000 I STORAGE  [signalProcessingThread] closeAllFiles() finished
[36mdatabase_1  |[0m 2017-12-08T16:57:59.922+0000 I STORAGE  [signalProcessingThread] shutdown: removing fs lock...
[36mdatabase_1  |[0m 2017-12-08T16:57:59.922+0000 I CONTROL  [signalProcessingThread] dbexit:  rc: 0
[36mdatabase_1  |[0m 2017-12-08T16:58:05.142+0000 I JOURNAL  [initandlisten] journal dir=/data/db/journal
[36mdatabase_1  |[0m 2017-12-08T16:58:05.142+0000 I JOURNAL  [initandlisten] recover : no journal files present, no recovery needed
[36mdatabase_1  |[0m 2017-12-08T16:58:05.151+0000 I JOURNAL  [durability] Durability thread started
[36mdatabase_1  |[0m 2017-12-08T16:58:05.151+0000 I JOURNAL  [journal writer] Journal writer thread started
[36mdatabase_1  |[0m 2017-12-08T16:58:05.158+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=c597a85cae60
[36mdatabase_1  |[0m 2017-12-08T16:58:05.158+0000 I CONTROL  [initandlisten] 
[36mdatabase_1  |[0m 2017-12-08T16:58:05.158+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
[36mdatabase_1  |[0m 2017-12-08T16:58:05.158+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
[36mdatabase_1  |[0m 2017-12-08T16:58:05.158+0000 I CONTROL  [initandlisten] 
[36mdatabase_1  |[0m 2017-12-08T16:58:05.158+0000 I CONTROL  [initandlisten] db version v3.0.2
[36mdatabase_1  |[0m 2017-12-08T16:58:05.158+0000 I CONTROL  [initandlisten] git version: 6201872043ecbbc0a4cc169b5482dcf385fc464f
[36mdatabase_1  |[0m 2017-12-08T16:58:05.158+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
[36mdatabase_1  |[0m 2017-12-08T16:58:05.158+0000 I CONTROL  [initandlisten] build info: Linux ip-10-171-120-232 3.2.0-4-amd64 #1 SMP Debian 3.2.46-1 x86_64 BOOST_LIB_VERSION=1_49
[36mdatabase_1  |[0m 2017-12-08T16:58:05.158+0000 I CONTROL  [initandlisten] allocator: tcmalloc
[36mdatabase_1  |[0m 2017-12-08T16:58:05.158+0000 I CONTROL  [initandlisten] options: {}
[36mdatabase_1  |[0m 2017-12-08T16:58:05.160+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
[36mdatabase_1  |[0m 2017-12-08T16:58:35.643+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.5:58918 #1 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:58:35.644+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.5:58920 #2 (2 connections now open)
[36mdatabase_1  |[0m 2017-12-08T16:58:35.645+0000 I NETWORK  [conn2] end connection 172.17.0.5:58920 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:58:35.645+0000 I NETWORK  [conn1] end connection 172.17.0.5:58918 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:59:02.388+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.1:47434 #3 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:59:02.388+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.1:47438 #4 (2 connections now open)
[36mdatabase_1  |[0m 2017-12-08T16:59:02.389+0000 I NETWORK  [conn4] end connection 172.17.0.1:47438 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:59:02.389+0000 I NETWORK  [conn3] end connection 172.17.0.1:47434 (0 connections now open)
[36mdatabase_1  |[0m 2017-12-08T16:59:02.395+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.1:47466 #5 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:59:02.395+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.1:47470 #6 (2 connections now open)
[36mdatabase_1  |[0m 2017-12-08T16:59:02.398+0000 I NETWORK  [conn6] end connection 172.17.0.1:47470 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:59:02.398+0000 I NETWORK  [conn5] end connection 172.17.0.1:47466 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:59:19.733+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.5:59054 #7 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:59:19.735+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.5:59058 #8 (2 connections now open)
[36mdatabase_1  |[0m 2017-12-08T16:59:19.736+0000 I NETWORK  [conn8] end connection 172.17.0.5:59058 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:59:19.736+0000 I NETWORK  [conn7] end connection 172.17.0.5:59054 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:59:25.642+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.1:47554 #9 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:59:25.642+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.1:47558 #10 (2 connections now open)
[36mdatabase_1  |[0m 2017-12-08T16:59:25.643+0000 I NETWORK  [conn10] end connection 172.17.0.1:47558 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:59:25.644+0000 I NETWORK  [conn9] end connection 172.17.0.1:47554 (0 connections now open)
[36mdatabase_1  |[0m 2017-12-08T16:59:25.650+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.1:47586 #11 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:59:25.650+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.1:47590 #12 (2 connections now open)
[36mdatabase_1  |[0m 2017-12-08T16:59:25.652+0000 I NETWORK  [conn11] end connection 172.17.0.1:47586 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T16:59:25.652+0000 I NETWORK  [conn12] end connection 172.17.0.1:47590 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T17:01:39.471+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.1:47788 #13 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T17:01:39.471+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.1:47792 #14 (2 connections now open)
[36mdatabase_1  |[0m 2017-12-08T17:01:39.472+0000 I NETWORK  [conn14] end connection 172.17.0.1:47792 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T17:01:39.472+0000 I NETWORK  [conn13] end connection 172.17.0.1:47788 (0 connections now open)
[36mdatabase_1  |[0m 2017-12-08T17:01:39.478+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.1:47820 #15 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T17:01:39.478+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.1:47824 #16 (2 connections now open)
[36mdatabase_1  |[0m 2017-12-08T17:01:39.480+0000 I NETWORK  [conn16] end connection 172.17.0.1:47824 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T17:01:39.480+0000 I NETWORK  [conn15] end connection 172.17.0.1:47820 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T17:01:59.557+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.5:59394 #17 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T17:01:59.560+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.5:59396 #18 (2 connections now open)
[36mdatabase_1  |[0m 2017-12-08T17:01:59.562+0000 I NETWORK  [conn18] end connection 172.17.0.5:59396 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T17:01:59.562+0000 I NETWORK  [conn17] end connection 172.17.0.5:59394 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T17:02:06.424+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.5:59428 #19 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T17:02:06.436+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.5:59434 #20 (2 connections now open)
[36mdatabase_1  |[0m 2017-12-08T17:02:06.438+0000 I NETWORK  [conn20] end connection 172.17.0.5:59434 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T17:02:06.438+0000 I NETWORK  [conn19] end connection 172.17.0.5:59428 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T17:50:43.107+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.1:51394 #21 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T17:50:43.108+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.1:51398 #22 (2 connections now open)
[36mdatabase_1  |[0m 2017-12-08T17:50:43.109+0000 I NETWORK  [conn22] end connection 172.17.0.1:51398 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T17:50:43.109+0000 I NETWORK  [conn21] end connection 172.17.0.1:51394 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T17:50:43.115+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.1:51426 #23 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T17:50:43.115+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.1:51430 #24 (2 connections now open)
[36mdatabase_1  |[0m 2017-12-08T17:50:43.117+0000 I NETWORK  [conn24] end connection 172.17.0.1:51430 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T17:50:43.117+0000 I NETWORK  [conn23] end connection 172.17.0.1:51426 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T17:51:17.108+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.1:51504 #25 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T17:51:17.109+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.1:51508 #26 (2 connections now open)
[36mdatabase_1  |[0m 2017-12-08T17:51:17.110+0000 I NETWORK  [conn26] end connection 172.17.0.1:51508 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T17:51:17.110+0000 I NETWORK  [conn25] end connection 172.17.0.1:51504 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T17:51:17.116+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.1:51536 #27 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T17:51:17.117+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.1:51540 #28 (2 connections now open)
[36mdatabase_1  |[0m 2017-12-08T17:51:17.119+0000 I NETWORK  [conn27] end connection 172.17.0.1:51536 (1 connection now open)
[36mdatabase_1  |[0m 2017-12-08T17:51:17.119+0000 I NETWORK  [conn28] end connection 172.17.0.1:51540 (1 connection now open)
Couldn't connect to Docker daemon - you might need to run `docker-machine stException in thread Thread-3:
Traceback (most recent call last):
  File "/home/jibin/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/jibin/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/compose/cli/log_printer.py", line 166, in tail_container_logs
    queue.put(QueueItem.new(presenter.color_func(wait_on_exit(container))))
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/compose/cli/log_printer.py", line 197, in wait_on_exit
    exit_code = container.wait()
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/compose/container.py", line 243, in wait
    return self.client.wait(self.id)
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/docker/api/container.py", line 1257, in wait
    res = self._post(url, timeout=timeout)
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/docker/api/client.py", line 187, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/jibin/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/jibin/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/compose/cli/log_printer.py", line 213, in watch_events
    for event in event_stream:
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/compose/project.py", line 399, in events
    container = Container.from_id(self.client, event['id'])
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/compose/container.py", line 42, in from_id
    return cls(client, client.inspect_container(id), has_been_inspected=True)
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/docker/api/container.py", line 760, in inspect_container
    self._get(self._url("/containers/{0}/json", container)), True
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/docker/api/client.py", line 191, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/jibin/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/jibin/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/compose/cli/log_printer.py", line 166, in tail_container_logs
    queue.put(QueueItem.new(presenter.color_func(wait_on_exit(container))))
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/compose/cli/log_printer.py", line 197, in wait_on_exit
    exit_code = container.wait()
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/compose/container.py", line 243, in wait
    return self.client.wait(self.id)
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/docker/api/container.py", line 1257, in wait
    res = self._post(url, timeout=timeout)
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/docker/api/client.py", line 187, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/jibin/anaconda2/lib/python2.7/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

[1A[2KStopping lockservice_database_1 ... [31merror[0m[1B
ERROR: for lockservice_lockserv_1  ('Connection aborted.', error(104, 'Connection reset by peer'))
Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.
Gracefully stopping... (press Ctrl+C again to force)
